events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:3001/;
            proxy_set_header Host $host;
        }

        location /api/ {
            proxy_pass http://doc-api:8000/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://frontend-app:3000/;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
